# Generated by Django 4.0.4 on 2022-05-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcinario',
            new_name='Funcionario',
        ),
    ]
